[project]
name = "hsfd-data-vis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "streamlit>=1.45.1",
    "plotly==6.1.2",
    "seaborn==0.13.2"
]
